# Generated by Django 6.0 on 2026-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageLink',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
