# Generated by Django 6.0 on 2026-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageLink',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg', max_length=255),
        ),
    ]
