# Generated by Django 6.0 on 2026-02-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvestDate', models.DateField()),
                ('stockPlace', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('limitationDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurementDate', models.DateField()),
                ('stockPlace', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('limitationDate', models.DateField(null=True)),
                ('purchaseCost', models.FloatField()),
            ],
        ),
    ]
