# Generated by Django 6.0 on 2026-03-27 23:52

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_crop_procurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitOfMeasurement',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
