# Generated by Django 6.0 on 2026-03-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_name_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='limitationDate',
            new_name='expirationDate',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='harvestDate',
            new_name='produceDate',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='stockPlace',
            new_name='storageLocation',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='stockPlace',
            new_name='storagePlace',
        ),
    ]
