# Generated by Django 6.0 on 2026-03-29 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_rename_limitationdate_crop_expirationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
