# Generated by Django 6.0 on 2026-03-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_crop_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
