# Generated by Django 6.0 on 2026-03-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_procurement_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='expirationDate',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='produceDate',
            new_name='produce_date',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='storageLocation',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='limitationDate',
            new_name='limitation_date',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='procurementDate',
            new_name='procurement_date',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='purchaseCost',
            new_name='purchase_cost',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='storagePlace',
            new_name='storage_location',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imageLink',
            new_name='image_link',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unitOfMeasurement',
            new_name='unit_of_measurement',
        ),
    ]
