# Generated by Django 6.0 on 2026-03-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_expirationdate_crop_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
