# Generated by Django 6.0 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurement',
            old_name='limitation_date',
            new_name='expiration_date',
        ),
    ]
